# SPDX-License-Identifier: GPL-3.0-or-later
# Author: Pavel Círus



schema_version = "1.0.0"

id = "asset_automation_tools"
version = "0.0.5"
name = "Asset Automation Tools"
tagline = "LOD, Shadow & Collision generation toolkit for assets"
maintainer = """Pavel Círus (Paul) <pavel.cirus@scssoft.com>"""

type = "add-on"

blender_version_min = "5.0.1"

license = ["SPDX:GPL-3.0-or-later"]

copyright = [
    "2026 Pavel Círus, All Rights Reserved.",
]
 
tags = ["Mesh", "Object"]
 
[build]
paths_exclude_pattern = [
    "*.blend1",
    "__pycache__/",
    ".*",
    "*.zip",
    "*.ps1",
    ".build_number",
    "*.code-workspace",
    ".vscode/",
    "*.md",
]
